### ISSUE TITLE
Line break?

### ISSUE THREAD

**Issue by cendt** [wilkox/treemapify#13]
Dear wilkox,
is it possible to allow line breaks for the text inside the boxes? By default, if a label is to long, the box simply stays empty. Even when the label contains of several words which could be split into several lines easily.
Best
Christian

**Comment by wilkox** [comment]
Thanks for the report Christian. `geom_treemap_text` has an option `reflow = T` that will reflow the text to fit a box. The documentation for [ggfittext](package) has some more details. Try it out and let me know if it fixes your problem!
