### ISSUE TITLE
Can't download successfully

### ISSUE THREAD

**Issue by FisherPang** [wilkox/treemapify#14]
> install_github('wilkox/ggfittext')
Downloading GitHub repo wilkox/ggfittext@master
from URL https://api.github.com/repos/wilkox/ggfittext/zipball/master
Installing ggfittext
"C:/PROGRA~1/R/R-3.4.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL "C:/Users/Fisher  \
  Pang/AppData/Local/Temp/RtmpQFpfSo/devtools32002db32240/wilkox-ggfittext-d3646e4" --library="C:/Users/Fisher Pang/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'ggfittext' ...
** R
Error in parse(outFile) : invalid multibyte character in parser at line 157
ERROR: unable to collate and parse R files for package 'ggfittext'
* removing 'C:/Users/Fisher Pang/Documents/R/win-library/3.4/ggfittext'

**Comment by wilkox** [comment]
Thanks for the report @FisherPang. Could you please run `Sys.getlocale(category = "LC_ALL")` and post the output?

**Comment by FisherPang** [comment]
Hi, Wilkox, thanks for helps. My default languages is Chineses. The output is as followings:

LC_COLLATE=Chinese (Simplified)_China.936;
LC_CTYPE=Chinese (Simplified)_China.936;
LC_MONETARY=Chinese (Simplified)_China.936;
LC_NUMERIC=C;
LC_TIME=Chinese (Simplified)_China.936

any solution for this issue?

**Comment by wilkox** [comment]
I think I've fixed it – try installing with this command:
```r
install_github('wilkox/ggfittext', ref = 'utf-8')
```
and let me know if it works.

**Comment by FisherPang** [comment]
Hi, wilkox, the outcome is as followings:

Downloading GitHub repo wilkox/ggfittext@utf-8
from URL https://api.github.com/repos/wilkox/ggfittext/zipball/utf-8
Installing ggfittext
"C:/PROGRA~1/R/R-3.4.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL "C:/Users/Fisher  \
  Pang/AppData/Local/Temp/Rtmpo9wgXz/devtools1a6c3f50584b/wilkox-ggfittext-5e84e48" --library="C:/Users/Fisher Pang/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'ggfittext' ...
** R
** tests
** preparing package for lazy loading
** help
Warning: C:/Users/Fisher Pang/AppData/Local/Temp/Rtmpo9wgXz/devtools1a6c3f50584b/wilkox-ggfittext-5e84e48/man/geom_fit_text.Rd:72: unknown macro '\n'
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (ggfittext)

Many thanks for the helps.

**Comment by FisherPang** [comment]
OMG, the 'ggfittext' can be installed successfully, but unfortunately, the 'treemapify' is facing the same issue.

**Comment by wilkox** [comment]
I've just made a similar fix to treemapify. Try

```r
install_github('wilkox/treemapify', ref = 'utf-8')
```

and let me know if it works. Thanks for your patience in solving this!

**Comment by FisherPang** [comment]
> install_github('wilkox/treemapify', ref = 'utf-8')
Downloading GitHub repo wilkox/treemapify@utf-8
from URL https://api.github.com/repos/wilkox/treemapify/zipball/utf-8
Installing treemapify
"C:/PROGRA~1/R/R-3.4.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL "C:/Users/Fisher  \
  Pang/AppData/Local/Temp/Rtmpo9wgXz/devtools1a6c5019275d/wilkox-treemapify-4207852" --library="C:/Users/Fisher Pang/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'treemapify' ...
** R
** data
*** moving datasets to lazyload DB
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (treemapify)

That's fantastic. Thank you Wilkox.
