### ISSUE TITLE
Is there a reason to require R ≥ 3.4.1?

### ISSUE THREAD

**Issue by jbkunst** [wilkox/treemapify#16]
Hi @wilkox 

Thanks for the package!

Is there a reason to require the last R version? Sometimes upgrade R have a big cost (for example when you teach R in a lab).

Thanks,

**Comment by wilkox** [comment]
Hi @jbkunst. Thanks for raising this. I've had other requests by email to reduce the version requirement so obviously this is an issue for many people. I'm going to try and reduce the requirement for treemapify and ggfittext to R ≥ 3.1, but I want to do some more testing first.

**Comment by tiernanmartin** [comment]
Any update on this?

**Comment by wilkox** [comment]
I'm working on getting an R ≥ 3.1-tested version of [ggfittext](https://github.com/wilkox/ggfittext) (which is upstream of this package) onto CRAN. Once that's done I can submit a similar treemapify update.

In the meantime the development version of treemapify works on ≥ 3.1 – you can try installing it with `devtools::install_github('wilkox/treemapify')`.

**Comment by wilkox** [comment]
treemapify v2.4.0 requiring R ≥ 3.1 is now available on CRAN.
