### ISSUE TITLE
Error while trying to replicate the tuto

### ISSUE THREAD

**Issue by gse-cc-git** [wilkox/treemapify#2]
Hello,
I got this error when I tried to replicate the tutorial (both with the G20 and my own dataset)
__Error: invalid (do_set) left-hand side to assignment__

It occurs when I am trying to run the ggplotify function.

sessionInfo():
>R version 3.1.2 (2014-10-31)
>Platform: x86_64-w64-mingw32/x64 (64-bit)
>attached base packages:
>[1] splines   grid      stats     graphics  grDevices utils     datasets  methods   base     
>other attached packages:
> [1] data.table_1.9.4 treemapify_0.1   reshape2_1.4     devtools_1.6.1   Hmisc_3.16-0     Formula_1.2-1   
> [7] survival_2.37-7  lattice_0.20-29  knitr_1.9        stringr_0.6.2    magrittr_1.5     rvest_0.2.0     
>[13] httr_0.5         XML_3.98-1.1     ggplot2_1.0.0    tidyr_0.2.0      dplyr_0.4.1      plyr_1.8.1      
>loaded via a namespace (and not attached):
 >[1] acepack_1.3-3.3     assertthat_0.1      chron_2.3-45        cluster_1.15.3      colorspace_1.2-4   
 >[6] DBI_0.3.1           digest_0.6.4        evaluate_0.5.5      foreign_0.8-61      formatR_1.0        
>[11] gridExtra_0.9.1     gtable_0.1.2        latticeExtra_0.6-26 lazyeval_0.1.10     MASS_7.3-35        
>[16] memoise_0.2.1       munsell_0.4.2       nnet_7.3-8          parallel_3.1.2      proto_0.3-10       
>[21] R6_2.0.1            RColorBrewer_1.0-5  Rcpp_0.11.3         rpart_4.1-8         scales_0.2.4       
>[26] tools_3.1.2 

thanks for your work and your help.

**Comment by gse-cc-git** [comment]
I found my problem !
It has to do with summarise and mutate functions.
Since the package dplyr was loaded, the functions were not those from plyr.
I obtained the correct treemap after taking that into account.

Sorry for the issue.

**Comment by wilkox** [comment]
No worries :smile: Let me know if you have any more trouble.
