### ISSUE TITLE
Request max.size argument for geom_..._text

### ISSUE THREAD

**Issue by geotheory** [wilkox/treemapify#24]
No big explanation needed.  There are min.size arguments.  It would be nice to have max options too :)

**Comment by wilkox** [comment]
Thanks @geotheory. Do you mean an argument that would hide text over a certain size, or that would grow text up to a certain size but not larger? If the latter this should already be achievable with a size aesthetic and `grow = F`.

**Comment by geotheory** [comment]
Ah that works perfectly, thanks!
