### ISSUE TITLE
Passing variables to subgroup doesn't work

### ISSUE THREAD

**Issue by GregorDeCillia** [wilkox/treemapify#25]
I currently develop an R package depending on treemaplify and some functionality broke due to [changes](https://github.com/wilkox/treemapify/commit/f29b1439c69ffa7a84b3a054d19590f1c30895e0#diff-3fc8db0254c19d753314145ef4758133L70) in f29b1439c69ffa7a84b3a054d19590f1c30895e0. Now I'm trying to rewrite the functionality with the new (group, subgroup) interface and ran into an issue which seems like a bug to me. When I save a column to a string variable and pass that variable to the subgroup argument of `treemapify`, I get an error

    treemapify(mtcars, area = "wt", subgroup = "am")
    #> expected output of size 32 x 14

    am_string <- "am"
    treemapify(mtcars, area = "wt", subgroup = am_string)
    #> Error in `[.default`(data, subgroups[[1]]) : 
    #>   invalid subscript type 'symbol'

**Comment by GregorDeCillia** [comment]
I was using the following call

    dat <- treemapify(dat, area=x@area, fill=x@fill, label=x@key, group=x@gruppe)

where `x` is some S4 class capturing plot parameters. I totally don't mind reworking my code since the subgroup functionality seems like a very handy addition.

**Comment by wilkox** [comment]
Just pushed a dev release (58e6650, v2.5.0.9001) that restores `fill` and `label` as deprecated arguments, and `group` as an alias for `subgroup`. Would this fix the issue? I'll probably publish it to CRAN soon regardless to fix backwards compatibility for anyone who was calling against those arguments.

**Comment by GregorDeCillia** [comment]
Yes, the fix you provided in 899518c worked out well. As I said, I don't mind the interface changes and that was also not the reason I filed this issue - just the fact that I couldn't pass variables. 

I've already adapted my project to an extend where I don't need the deprcated arguments anymore, but I can test them later today if you are interested.

**Comment by wilkox** [comment]
No need to test if you’re not going to use the changes, I just wanted to make sure there wasn’t another bug I didn’t know about. Thanks a lot for reporting this!
