### ISSUE TITLE
Can the tile placement proceeds from other directions?

### ISSUE THREAD

**Issue by Yuanchao-Xu** [wilkox/treemapify#30]
Hi David,

In your description, it's said 

> placement proceeds from the bottom left
corner, filling alternately rightwards then upwards until all tiles are placed. 

I was wondering is there other direction for the placement, e.g., from top left?

Thanks

**Comment by wilkox** [comment]
Hi Yuanchao. It's not currently possible to control the starting position and direction of tile placement, but it wouldn't be hard to add this feature. Can I ask in what sort of situation you would want to change these parameters? Would you want the parameters to apply to the whole treemap, or to be able to control them independently for different subgroups?

**Comment by Yuanchao-Xu** [comment]
Hi David,

Thanks, If possible, my case is from top left then filling alternately downward then rightward. For subgroups, it'll be perfect if subgroups follow the same rule.
\

**Comment by wilkox** [comment]
Sorry if my question wasn't clear. What I'm trying to understand is: in what situation is column-first tile placement and starting from the top left corner better than the current default? Is it an aesthetic choice or is there a practical reason to prefer this layout?

**Comment by Yuanchao-Xu** [comment]
Oh I didn't get your question before. There isn't a specific reason, just other treemap softwares put it like that, e.g., treemap, tableau and power BI, and it looks natural and in accordance with people's reading habit.

Current default one is OK, just was wondering if there's a parameter controlling the way it places.

**Comment by wilkox** [comment]
Thanks Yuanchao. I’m going to add arguments to let you specify the starting corner and row-first va column-first placement. I’ll update this issue when the feature is released.

**Comment by wilkox** [comment]
The latest development version v2.5.0.9004 adds a `start` argument to all the geoms that lets you specify the starting corner (`bottomleft`, `topleft`, `topright` or `bottomright`), and a `layout` argument that lets you choose a row-first (`srow`) or column-first (`scol`) squarified layout. You can install the development version with `devtools::install_github("wilkox/treemapify")`. Does this solve your issue?

**Comment by Yuanchao-Xu** [comment]
Thanks David! I've just tried that, that's perfect!
