### ISSUE TITLE
Ignoring unknown parameters: radius

### ISSUE THREAD

**Issue by zh-Bian** [wilkox/treemapify#42]
I see there is a parameter 'radius', however it didn't work. I need to change the square to rounded corners.How could I do this? Thank you.
ggplot(data=data,mapping = aes(area=Freq,fill=Var1)) +
  geom_treemap(start='bottomright',show.legend=F,radius = grid::unit(2, "mm")) @hrbrmstr @wilkox @stijnvanhoey

**Comment by hrbrmstr** [comment]
```r
library(ggplot2)
library(hrbrthemes)
library(treemapify)

ggplot(G20) +
  geom_treemap(
    aes(
      area = gdp_mil_usd, 
      fill = region
    ),
    start = "bottomright",
    show.legend = FALSE, 
    radius = grid::unit(2, "mm"),
    color = "white",
    size = 5
  ) +
  theme_ipsum_gs(grid="")
```

![image](https://user-images.githubusercontent.com/509878/96999111-aa86a200-1502-11eb-911b-55ec2cd06618.png)


?

**Comment by wilkox** [comment]
@zh-Bian if you're still having this problem, could you please post a [reprex](https://reprex.tidyverse.org) including some sample data that shows the error? Thanks.
