### ISSUE TITLE
Color aesthetics not showing up in legend?

### ISSUE THREAD

**Issue by jjbuonocore** [wilkox/treemapify#47]
I'm having some trouble getting the color aesthetic to show up in the legend. Working with the G20 example:

`ggplot2::ggplot(G20, ggplot2::aes(area = gdp_mil_usd, fill = region)) +
  geom_treemap()

# works just fine`

![1](https://github.com/wilkox/treemapify/assets/68395771/9c6d9554-1600-420c-bf34-dcb815d9cdcd)

ggplot(G20, ggplot2::aes(area = gdp_mil_usd, fill = region, color = econ_classification)) +
  geom_treemap() + 
  scale_color_manual(values = c("red", "black"))

# color does not show up in the legend

![color and fill](https://github.com/wilkox/treemapify/assets/68395771/2ba7bbfc-7c11-4974-9674-09b8cf1ff2bd)

ggplot(G20, ggplot2::aes(area = gdp_mil_usd, fill = region, color = econ_classification, linetype = econ_classification)) +
  geom_treemap() + 
  scale_color_manual(values = c("red", "black")) +
  scale_linetype_manual(values = c(1,3)) +
  guides(color = guide_legend(override.aes = list(color = c("red", "black"))))

# fill shows up in a legend, along with linetype, but color does not`

![color fill linetype](https://github.com/wilkox/treemapify/assets/68395771/eea86983-286d-45d0-872f-9c66c7e5a48a)

**Comment by wilkox** [comment]
Thanks for reporting this @jjbuonocore! I've pushed a fix to the development version and this will be released on CRAN soon.

``` r
library(ggplot2)
library(treemapify)

ggplot(G20, ggplot2::aes(area = gdp_mil_usd, fill = region, 
                         color = econ_classification)) +
  geom_treemap() +
  scale_color_manual(values = c("red", "black"))
```

![](https://i.imgur.com/y7v5lUX.png)

``` r

ggplot(G20, ggplot2::aes(area = gdp_mil_usd, fill = region, 
                         color = econ_classification, 
                         linetype = econ_classification)) +
  geom_treemap() +
  scale_color_manual(values = c("red", "black")) +
  scale_linetype_manual(values = c(1,3)) +
  guides(color = guide_legend(override.aes = list(color = c("red", "black"))))
```

![](https://i.imgur.com/yGYBiXW.png)

<sup>Created on 2023-09-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
