### ISSUE TITLE
Fixed size labels

### ISSUE THREAD

**Issue by aviast** [wilkox/treemapify#5]
Hello, I've just installed this package as I need to use treemaps in a shinydashboard application. Thank you for putting this together!!! Because I'm using shiny I'd rather use ggvis than ggplot2 to render the final plot so I may come up with some code to achieve this in the near future.

The first issue that I have, however, is the variable-sized labels. I don't thnk this adds anything to the plot - the small labels are illegible and the label sizes don't appear to be proportional to the tile size as I suspect they should be (in my case I have a small tile that has a large label next to a large tile which has a smaller label).

I'd like to raise a feature request to have the option for fixed-size labels. (Basically the same behaviour as the plots produced with the treemap package.)

Regards,

Michael

**Comment by wilkox** [comment]
Thanks for the suggestion Michael. I've added two new arguments (`label.size.fixed` and `group.label.size.fixed`) in e504c23.

I don't recommend using ggplotify in production, or in situations where you won't have a chance to manually check and edit the plot. It was intended only as a convenience function for checking the output of treemapify, not for producing publication or production-quality graphics. One day I might tidy it up to produce reliably high quality graphics, but automatically sizing the text labels for both legibility and arrangement in the plot is too big a problem for now.
