### ISSUE TITLE
Wrap text in geom_treemap_text?

### ISSUE THREAD

**Issue by py** [wilkox/treemapify#9]
Great package. It's always nice to use the familiar grammar of graphics syntax.

I've been doing many treemaps lately using the `treemap` package. A nice feature of that package is that it will wrap label text onto multiple lines to preserve legibility.

Have you considered adding this as an option for the geom_treemap_text geom? I'll look at the code.

Thanks.

**Comment by wilkox** [comment]
This is a great idea. I'll have a look at adding something like `geom_reflow_text` to [ggfittext](https://github.com/wilkox/ggfittext), then give `geom_treemap_text` an argument to invoke it.

**Comment by wilkox** [comment]
@py I've added a ‘reflow’ option to `geom_treemap_text` and `geom_treemap_subgroup_text`. Let me know if you find any issues. Thanks for the suggestion!

**Comment by py** [comment]
Great work. I tested it today and it's working. This helps me immensely.
Thank you!
